<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="multicluster"
    nsURI="http://krosskube/multicluster"
    nsPrefix="multicluster">

  <eClassifiers xsi:type="ecore:EEnum" name="PlacementPolicy">
    <eLiterals name="REPLICATED"/>
    <eLiterals name="DISTRIBUTED"/>
    <eLiterals name="BALANCED"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="ClusterSelector">
    <eStructuralFeatures xsi:type="ecore:EAttribute"
        name="matchLabels"
        upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute"
        name="matchExpressions"
        upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="MultiClusterResource" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference"
        name="clusterSelector"
        containment="true"
        eType="#//ClusterSelector"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute"
        name="placementPolicy"
        eType="#//PlacementPolicy"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="MultiClusterWorkload" abstract="true"
      eSuperTypes="#//MultiClusterResource"/>

  <eClassifiers xsi:type="ecore:EClass" name="MultiClusterDeployment"
      eSuperTypes="#//MultiClusterWorkload"/>

  <eClassifiers xsi:type="ecore:EClass" name="MultiClusterStatefulSet"
      eSuperTypes="#//MultiClusterWorkload"/>

  <eClassifiers xsi:type="ecore:EClass" name="MultiClusterDaemonSet"
      eSuperTypes="#//MultiClusterWorkload"/>

  <eClassifiers xsi:type="ecore:EClass" name="MultiClusterCronJob"
      eSuperTypes="#//MultiClusterWorkload"/>

  <eClassifiers xsi:type="ecore:EClass" name="MultiClusterPod"
      eSuperTypes="#//MultiClusterWorkload"/>

  <!-- Network MultiCluster Resources -->
  <eClassifiers xsi:type="ecore:EClass" name="MultiClusterNetwork" abstract="true"
      eSuperTypes="#//MultiClusterResource"/>

  <eClassifiers xsi:type="ecore:EClass" name="MultiClusterService"
      eSuperTypes="#//MultiClusterNetwork"/>

  <eClassifiers xsi:type="ecore:EClass" name="MultiClusterIngress"
      eSuperTypes="#//MultiClusterNetwork"/>

  <!-- Storage MultiCluster Resources -->
  <eClassifiers xsi:type="ecore:EClass" name="MultiClusterStorage" abstract="true"
      eSuperTypes="#//MultiClusterResource"/>

  <eClassifiers xsi:type="ecore:EClass" name="MultiClusterPersistentVolume"
      eSuperTypes="#//MultiClusterStorage"/>

  <eClassifiers xsi:type="ecore:EClass" name="MultiClusterPersistentVolumeClaim"
      eSuperTypes="#//MultiClusterStorage"/>

  <!-- Security MultiCluster Resources -->
  <eClassifiers xsi:type="ecore:EClass" name="MultiClusterSecurity" abstract="true"
      eSuperTypes="#//MultiClusterResource"/>

  <eClassifiers xsi:type="ecore:EClass" name="MultiClusterRole"
      eSuperTypes="#//MultiClusterSecurity"/>

  <eClassifiers xsi:type="ecore:EClass" name="MultiClusterRoleBinding"
      eSuperTypes="#//MultiClusterSecurity"/>

  <eClassifiers xsi:type="ecore:EClass" name="MultiClusterSecret"
      eSuperTypes="#//MultiClusterSecurity"/>

  <eClassifiers xsi:type="ecore:EClass" name="MultiClusterConfigMap"
      eSuperTypes="#//MultiClusterSecurity"/>

</ecore:EPackage>