<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="config"
    nsURI="http://krosskube/kubernetes/config"
    nsPrefix="config">

  <eClassifiers xsi:type="ecore:EClass" name="ConfigMap"/>
  <eClassifiers xsi:type="ecore:EClass" name="Secret"/>

</ecore:EPackage>
