<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="storage"
    nsURI="http://krosskube/kubernetes/storage"
    nsPrefix="storage">

  <eClassifiers xsi:type="ecore:EClass" name="ExternalStorage"/>

  <eClassifiers xsi:type="ecore:EClass" name="PersistentVolume">
    <eStructuralFeatures xsi:type="ecore:EReference"
        name="externalStorage"
        eType="#//ExternalStorage"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="PersistentVolumeClaim">
    <eStructuralFeatures xsi:type="ecore:EReference"
        name="persistentVolume"
        eType="#//PersistentVolume"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Volume">
    <eStructuralFeatures xsi:type="ecore:EReference"
        name="claim"
        eType="#//PersistentVolumeClaim"/>
    <eStructuralFeatures xsi:type="ecore:EReference"
        name="secret"
        eType="ecore:EClass ../../metamodel_subpackages/kubernetes.config.ecore#//Secret"/>
    <eStructuralFeatures xsi:type="ecore:EReference"
        name="configMap"
        eType="ecore:EClass ../../metamodel_subpackages/kubernetes.config.ecore#//ConfigMap"/>
  </eClassifiers>

</ecore:EPackage>