/**
 */
package multicluster.provider;

import java.util.ArrayList;
import java.util.Collection;

import multicluster.util.MulticlusterAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class MulticlusterItemProviderAdapterFactory extends MulticlusterAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public MulticlusterItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link multicluster.ClusterSelector} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClusterSelectorItemProvider clusterSelectorItemProvider;

	/**
	 * This creates an adapter for a {@link multicluster.ClusterSelector}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClusterSelectorAdapter() {
		if (clusterSelectorItemProvider == null) {
			clusterSelectorItemProvider = new ClusterSelectorItemProvider(this);
		}

		return clusterSelectorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link multicluster.MultiClusterDeployment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultiClusterDeploymentItemProvider multiClusterDeploymentItemProvider;

	/**
	 * This creates an adapter for a {@link multicluster.MultiClusterDeployment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMultiClusterDeploymentAdapter() {
		if (multiClusterDeploymentItemProvider == null) {
			multiClusterDeploymentItemProvider = new MultiClusterDeploymentItemProvider(this);
		}

		return multiClusterDeploymentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link multicluster.MultiClusterStatefulSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultiClusterStatefulSetItemProvider multiClusterStatefulSetItemProvider;

	/**
	 * This creates an adapter for a {@link multicluster.MultiClusterStatefulSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMultiClusterStatefulSetAdapter() {
		if (multiClusterStatefulSetItemProvider == null) {
			multiClusterStatefulSetItemProvider = new MultiClusterStatefulSetItemProvider(this);
		}

		return multiClusterStatefulSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link multicluster.MultiClusterDaemonSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultiClusterDaemonSetItemProvider multiClusterDaemonSetItemProvider;

	/**
	 * This creates an adapter for a {@link multicluster.MultiClusterDaemonSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMultiClusterDaemonSetAdapter() {
		if (multiClusterDaemonSetItemProvider == null) {
			multiClusterDaemonSetItemProvider = new MultiClusterDaemonSetItemProvider(this);
		}

		return multiClusterDaemonSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link multicluster.MultiClusterCronJob} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultiClusterCronJobItemProvider multiClusterCronJobItemProvider;

	/**
	 * This creates an adapter for a {@link multicluster.MultiClusterCronJob}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMultiClusterCronJobAdapter() {
		if (multiClusterCronJobItemProvider == null) {
			multiClusterCronJobItemProvider = new MultiClusterCronJobItemProvider(this);
		}

		return multiClusterCronJobItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link multicluster.MultiClusterPod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultiClusterPodItemProvider multiClusterPodItemProvider;

	/**
	 * This creates an adapter for a {@link multicluster.MultiClusterPod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMultiClusterPodAdapter() {
		if (multiClusterPodItemProvider == null) {
			multiClusterPodItemProvider = new MultiClusterPodItemProvider(this);
		}

		return multiClusterPodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link multicluster.MultiClusterService} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultiClusterServiceItemProvider multiClusterServiceItemProvider;

	/**
	 * This creates an adapter for a {@link multicluster.MultiClusterService}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMultiClusterServiceAdapter() {
		if (multiClusterServiceItemProvider == null) {
			multiClusterServiceItemProvider = new MultiClusterServiceItemProvider(this);
		}

		return multiClusterServiceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link multicluster.MultiClusterIngress} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultiClusterIngressItemProvider multiClusterIngressItemProvider;

	/**
	 * This creates an adapter for a {@link multicluster.MultiClusterIngress}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMultiClusterIngressAdapter() {
		if (multiClusterIngressItemProvider == null) {
			multiClusterIngressItemProvider = new MultiClusterIngressItemProvider(this);
		}

		return multiClusterIngressItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link multicluster.MultiClusterPersistentVolume} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultiClusterPersistentVolumeItemProvider multiClusterPersistentVolumeItemProvider;

	/**
	 * This creates an adapter for a {@link multicluster.MultiClusterPersistentVolume}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMultiClusterPersistentVolumeAdapter() {
		if (multiClusterPersistentVolumeItemProvider == null) {
			multiClusterPersistentVolumeItemProvider = new MultiClusterPersistentVolumeItemProvider(this);
		}

		return multiClusterPersistentVolumeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link multicluster.MultiClusterPersistentVolumeClaim} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultiClusterPersistentVolumeClaimItemProvider multiClusterPersistentVolumeClaimItemProvider;

	/**
	 * This creates an adapter for a {@link multicluster.MultiClusterPersistentVolumeClaim}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMultiClusterPersistentVolumeClaimAdapter() {
		if (multiClusterPersistentVolumeClaimItemProvider == null) {
			multiClusterPersistentVolumeClaimItemProvider = new MultiClusterPersistentVolumeClaimItemProvider(this);
		}

		return multiClusterPersistentVolumeClaimItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link multicluster.MultiClusterRole} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultiClusterRoleItemProvider multiClusterRoleItemProvider;

	/**
	 * This creates an adapter for a {@link multicluster.MultiClusterRole}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMultiClusterRoleAdapter() {
		if (multiClusterRoleItemProvider == null) {
			multiClusterRoleItemProvider = new MultiClusterRoleItemProvider(this);
		}

		return multiClusterRoleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link multicluster.MultiClusterRoleBinding} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultiClusterRoleBindingItemProvider multiClusterRoleBindingItemProvider;

	/**
	 * This creates an adapter for a {@link multicluster.MultiClusterRoleBinding}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMultiClusterRoleBindingAdapter() {
		if (multiClusterRoleBindingItemProvider == null) {
			multiClusterRoleBindingItemProvider = new MultiClusterRoleBindingItemProvider(this);
		}

		return multiClusterRoleBindingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link multicluster.MultiClusterSecret} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultiClusterSecretItemProvider multiClusterSecretItemProvider;

	/**
	 * This creates an adapter for a {@link multicluster.MultiClusterSecret}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMultiClusterSecretAdapter() {
		if (multiClusterSecretItemProvider == null) {
			multiClusterSecretItemProvider = new MultiClusterSecretItemProvider(this);
		}

		return multiClusterSecretItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link multicluster.MultiClusterConfigMap} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultiClusterConfigMapItemProvider multiClusterConfigMapItemProvider;

	/**
	 * This creates an adapter for a {@link multicluster.MultiClusterConfigMap}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMultiClusterConfigMapAdapter() {
		if (multiClusterConfigMapItemProvider == null) {
			multiClusterConfigMapItemProvider = new MultiClusterConfigMapItemProvider(this);
		}

		return multiClusterConfigMapItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (clusterSelectorItemProvider != null) clusterSelectorItemProvider.dispose();
		if (multiClusterDeploymentItemProvider != null) multiClusterDeploymentItemProvider.dispose();
		if (multiClusterStatefulSetItemProvider != null) multiClusterStatefulSetItemProvider.dispose();
		if (multiClusterDaemonSetItemProvider != null) multiClusterDaemonSetItemProvider.dispose();
		if (multiClusterCronJobItemProvider != null) multiClusterCronJobItemProvider.dispose();
		if (multiClusterPodItemProvider != null) multiClusterPodItemProvider.dispose();
		if (multiClusterServiceItemProvider != null) multiClusterServiceItemProvider.dispose();
		if (multiClusterIngressItemProvider != null) multiClusterIngressItemProvider.dispose();
		if (multiClusterPersistentVolumeItemProvider != null) multiClusterPersistentVolumeItemProvider.dispose();
		if (multiClusterPersistentVolumeClaimItemProvider != null) multiClusterPersistentVolumeClaimItemProvider.dispose();
		if (multiClusterRoleItemProvider != null) multiClusterRoleItemProvider.dispose();
		if (multiClusterRoleBindingItemProvider != null) multiClusterRoleBindingItemProvider.dispose();
		if (multiClusterSecretItemProvider != null) multiClusterSecretItemProvider.dispose();
		if (multiClusterConfigMapItemProvider != null) multiClusterConfigMapItemProvider.dispose();
	}

}
