<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="security"
    nsURI="http://krosskube/kubernetes/security"
    nsPrefix="security">

  <eClassifiers xsi:type="ecore:EClass" name="Role"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceAccount"/>

  <eClassifiers xsi:type="ecore:EClass" name="RoleBinding">
    <eStructuralFeatures xsi:type="ecore:EReference"
        name="role"
        eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EReference"
        name="serviceAccount"
        eType="#//ServiceAccount"/>
  </eClassifiers>

</ecore:EPackage>
