<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="runtime"
    nsURI="http://krosskube/kubernetes/runtime"
    nsPrefix="runtime">

  <!-- Namespace -->
  <eClassifiers xsi:type="ecore:EClass" name="Namespace"/>

  <!-- Environment Variable -->
  <eClassifiers xsi:type="ecore:EClass" name="EnvironmentVariable">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nameRequired nameValid"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="nameRequired" value="not name.oclIsUndefined() and name.size() > 0"/>
      <details key="nameValid" value="name.matches('[A-Za-z_][A-Za-z0-9_]*')"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute"
        name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute"
        name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Docker Image -->
  <eClassifiers xsi:type="ecore:EClass" name="DockerImage"/>

  <!-- Container -->
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="imageRequired environmentVariableNamesUnique environmentVariableNamesValid"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="imageRequired" value="not dockerImage.oclIsUndefined()"/>
      <details key="environmentVariableNamesUnique" value="environmentVariables->isUnique(env | env.name)"/>
      <details key="environmentVariableNamesValid" value="environmentVariables->forAll(env | env.name.matches('[A-Z_][A-Z0-9_]*'))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference"
        name="environmentVariables"
        upperBound="-1"
        containment="true"
        eType="#//EnvironmentVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference"
        name="dockerImage"
        eType="#//DockerImage"/>
  </eClassifiers>

  <!-- Pod -->
  <eClassifiers xsi:type="ecore:EClass" name="Pod">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="containersNotEmpty containerNamesUnique namespaceFormat"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="containersNotEmpty" value="containers->size() > 0"/>
      <details key="containerNamesUnique" value="containers->isUnique(c | c.name)"/>
      <details key="namespaceFormat" value="namespace.oclIsUndefined() or namespace.name.matches('[a-z0-9]([-a-z0-9]*[a-z0-9])?')"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference"
        name="containers"
        upperBound="-1"
        containment="true"
        eType="#//Container"/>
    <eStructuralFeatures xsi:type="ecore:EReference"
        name="namespace"
        eType="#//Namespace"/>
    <eStructuralFeatures xsi:type="ecore:EReference"
        name="volumes"
        upperBound="-1"
        eType="ecore:EClass ./kubernetes.storage.ecore#//Volume"/>
    <eStructuralFeatures xsi:type="ecore:EReference"
        name="serviceAccount"
        eType="ecore:EClass ./kubernetes.security.ecore#//ServiceAccount"/>
  </eClassifiers>

  <!-- Replica Set -->
  <eClassifiers xsi:type="ecore:EClass" name="ReplicaSet">
    <eStructuralFeatures xsi:type="ecore:EReference"
        name="pods"
        upperBound="-1"
        containment="true"
        eType="#//Pod"/>
  </eClassifiers>

  <!-- Deployment -->
  <eClassifiers xsi:type="ecore:EClass" name="Deployment">
    <eStructuralFeatures xsi:type="ecore:EReference"
        name="replicaSet"
        containment="true"
        eType="#//ReplicaSet"/>
  </eClassifiers>

  <!-- Stateful Set -->
  <eClassifiers xsi:type="ecore:EClass" name="StatefulSet">
    <eStructuralFeatures xsi:type="ecore:EReference"
        name="pods"
        upperBound="-1"
        containment="true"
        eType="#//Pod"/>
  </eClassifiers>

  <!-- Daemon Set -->
  <eClassifiers xsi:type="ecore:EClass" name="DaemonSet">
    <eStructuralFeatures xsi:type="ecore:EReference"
        name="pods"
        upperBound="-1"
        containment="true"
        eType="#//Pod"/>
  </eClassifiers>

  <!-- Job-->
  <eClassifiers xsi:type="ecore:EClass" name="Job"/>

  <!-- CronJob -->
  <eClassifiers xsi:type="ecore:EClass" name="CronJob">
    <eStructuralFeatures xsi:type="ecore:EReference"
        name="jobs"
        upperBound="-1"
        containment="true"
        eType="#//Job"/>
  </eClassifiers>

  <!-- Service -->
  <eClassifiers xsi:type="ecore:EClass" name="Service">
    <eStructuralFeatures xsi:type="ecore:EReference"
        name="pods"
        upperBound="-1"
        eType="#//Pod"/>
  </eClassifiers>

  <!-- Ingress -->
  <eClassifiers xsi:type="ecore:EClass" name="Ingress">
    <eStructuralFeatures xsi:type="ecore:EReference"
        name="services"
        upperBound="-1"
        eType="#//Service"/>
  </eClassifiers>

</ecore:EPackage>
